#:schema https://jj-vcs.github.io/jj/prerelease/config-schema.json
[git]

private-commits = "description(glob:'wip:*') | description(glob:'private:*')"
colocate = true
sign-on-push = true
write-change-id-header = true
