#:schema https://jj-vcs.github.io/jj/prerelease/config-schema.json
[ui]
editor = "/usr/bin/nvim"

pager = "delta"
paginate = "auto"
diff-formater = ":git"
#diff = "git"
#diff.tool = "delta"
default-command = "log"
#conflict-marker-style = "snapshot"
#diff-editor = "scm-diff-editor $left $right"
# TODO: remove after 0.37
revsets-use-glob-by-default = true

[colors]
# used in log_compact template
"todo" = { bg = "yellow", fg = "black" }
